site-link: https://rodrigues.com.pt
site-name: Rodrigues
site-title: <a href="/"><h1>rodrigues.com.pt</h1></a>
site-about: 
copyright-line: © 2022-{{{current-year}}} Bruno D. Rodrigues – All Rights Reserved
google-analytics: G-980YW0Z51E
meta-description: Rodrigues
meta-keywords: Rodrigues, Bruno Rodrigues
